### PR TITLE
update with examples for 2024 data

### PR DESCRIPTION
**Pull request by PascalBaertschi**

### CODE REVIEW

**Comment by ferencek** [comment]
@PascalBaertschi, there is a bunch of binary `__pycache__/crab_*.pyc` files that would be brought in by this PR. Those should be removed. Is the log file `crab.log` also needed?

**Comment by PascalBaertschi** [comment]
Thanks @ferencek, I removed them and also some other code not needed anymore. I also updated the README so that it contains all the information about the task.

**Comment by ferencek** [comment]
Do you expect any additional updates to this PR?

**Comment by PascalBaertschi** [comment]
No, I don't think so. Should I merge it?

**Comment by ferencek** [comment]
OK , I just did it. Note that I used the "Squash and merge" method which then prevented unnecessary files from entering the repository history (normally, if some files are added in one commit and later removed in another, they effectively still enter the repository).

**Pull request merged**
